import Header from "../components/header";
import "../styles/global.css";

export const metadata = {
  title: "박수진의 포트폴리오",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
